version: "3.7"

services:
  kafka:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '25676:25676'
      - '15672:15672'
  postgres-task:
    image: postgres:11.8
    container_name: postgres-db-task
    ports:
      -  5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  postgres-user:
    image: postgres:11.8
    container_name: postgres-db-user
    ports:
      -  5433:5432
    environment:
      POSTGRES_PASSWORD: postgres

